antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'batch'
site:
  title: Spring Batch Reference
  url: https://docs.spring.io/spring-batch/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-batch
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [ main,'({5..9}).+({1..9}).x' ]
    tags: [ 'v({5..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))', '!(v5.0.+({0..9})?(-{RC,M}+({0..9})))','!(v5.1.0-M1)','!(v5.1.0-M2)', '!(v5.1.0-M3)', '!(v5.1.0-RC1)' ]
    start_path: spring-batch-docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-batch
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
    attribute-missing: 'warn'
    sourcemap: true
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/javadoc-extension'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
    format: pretty