name: Artifactory Staging

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version (5.2.x)"
        required: true

jobs:
  build:
    name: Stage release to Artifactory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          ref: '5.2.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Update release version
        run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.releaseVersion }}

      - name: Enforce release rules
        run: mvn org.apache.maven.plugins:maven-enforcer-plugin:enforce -Drules=requireReleaseDeps

      - name: Build with Maven
        run: mvn -DaltDeploymentRepository=local::file:deployment-repository --no-transfer-progress --batch-mode -Dmaven.test.skip=true deploy

      - name: Deploy to Artifactory
        uses: spring-io/artifactory-deploy-action@v0.0.2
        with:
          uri: 'https://repo.spring.io'
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          build-name: 'spring-batch-${{ github.event.inputs.releaseVersion }}'
          repository: 'libs-staging-local'
          folder: 'deployment-repository'
          signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
          signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
